apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ihrjr2cyd-nodejs
  janus-idp.io/tekton: ihrjr2cyd-nodejs
  backstage.io/kubernetes-id: ihrjr2cyd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ihrjr2cyd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
